version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MSSQL_HOST=db
      - MSSQL_PORT=1433
      - MSSQL_DATABASE=bookingDate
      - MSSQL_USERNAME=sa
      - MSSQL_PASSWORD=your-password

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=your-password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql