spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${MSSQL_HOST}:${MSSQL_PORT};database=${MSSQL_DATABASE};
    username: ${MSSQL_USERNAME}
    password: ${MSSQL_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  main:
    banner-mode: off

logging:
  level:
    root: warn
    org:
      hibernate:
        #        log sql statements
        sql: debug
        orm:
          jdbc:
            #            log the values from statements
            bind: trace
      springframework:
        security: DEBUG
server:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expire-milli: 604800000
  error:
    include-message: always
